//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerBtnRelationship
    {
        public int pbrId { get; set; }
        public int pbrPerMenuId { get; set; }
        public int pbrPerBtnId { get; set; }
        public int pbrPermission { get; set; }
        public bool pbrIsDel { get; set; }
        public System.DateTime pbrAddTime { get; set; }
    
        public virtual PermissionMenu PermissionMenu { get; set; }
        public virtual PermissionBtn PermissionBtn { get; set; }
        public virtual PermissionMenu PermissionMenu1 { get; set; }
    }
}
