//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolePerRelationship
    {
        public int rprId { get; set; }
        public int rprRoleId { get; set; }
        public Nullable<int> rprPerMenuId { get; set; }
        public Nullable<int> rprPerBtnId { get; set; }
        public Nullable<int> rprSpecialBtnId { get; set; }
    
        public virtual PermissionBtn PermissionBtn { get; set; }
        public virtual PermissionMenu PermissionMenu { get; set; }
        public virtual PermissionSpecialBtn PermissionSpecialBtn { get; set; }
        public virtual Role Role { get; set; }
    }
}
