//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAdmin
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CommonCRMEntities : DbContext
    {
        public CommonCRMEntities()
            : base("name=CommonCRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Department> Department { get; set; }
        public DbSet<Employee> Employee { get; set; }
        public DbSet<PerBtnRelationship> PerBtnRelationship { get; set; }
        public DbSet<PermissionBtn> PermissionBtn { get; set; }
        public DbSet<PermissionMenu> PermissionMenu { get; set; }
        public DbSet<PermissionSpecialBtn> PermissionSpecialBtn { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<RolePerRelationship> RolePerRelationship { get; set; }
        public DbSet<WorkFLow> WorkFLow { get; set; }
        public DbSet<WorkFlowApply> WorkFlowApply { get; set; }
        public DbSet<WorkFlowApplyDetail> WorkFlowApplyDetail { get; set; }
        public DbSet<WorkFlowBLLBranchNode> WorkFlowBLLBranchNode { get; set; }
        public DbSet<WorkFlowNode> WorkFlowNode { get; set; }
        public DbSet<WorkFlowNodeRole> WorkFlowNodeRole { get; set; }
    }
}
